name: CMake

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        path: 'clazy'

    - uses: actions/checkout@v4
      with:
        path: 'llvm'
        repository: 'llvm/llvm-project.git'
        ref: 'llvmorg-11.0.0'

    - name: Install Ninja
      run: choco install ninja -y

    - name: MSVC env
      run: |
        cmd /c "C:\\Program\ Files\ (x86)\\Microsoft\ Visual\ Studio\\2019\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat"

    - name: Configure CMake
      run: >
        cmake -B ${{ github.workspace }}/llvm/build -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}\llvm-install\
        -DLLVM_EXPORT_SYMBOLS_FOR_PLUGINS=ON
        -DLLVM_INCLUDE_EXAMPLES=OFF
        -DLLVM_TARGETS_TO_BUILD="X86"
        -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra"
        -DCMAKE_CXX_COMPILER=cl
        -DCMAKE_C_COMPILER=cl
        -DCMAKE_BUILD_TYPE=Release
        -G "Ninja" ${{ github.workspace }}/llvm/llvm

    - name: Build
      run: cmake --build ${{ github.workspace }}/llvm/build --config Release
